version: "3.8"
services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-java8-multiarch}
    volumes:
    - ./server_data:/data
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: FORGE
      DEBUG: "${DEBUG:-false}"
      VERSION: ${VERSION:-1.16.5}
      FORGE_VERSION: ${FORGE_VERSION:-36.2.34}
      GENERIC_PACK: /modpacks/DoctorWhoDalekExterminate-5.3.zip
      REMOVE_OLD_MODS: "${REMOVE_OLD_MODS:-false}"
    ports:
      - "25565:25565"
